schema_version: 1

context:
  version: "3.15.1"

package:
  name: guard-core
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/guard-core/guard_core-${{ version }}.tar.gz
  sha256: 82ac760d1baf0607fc38bae6a8fa9c858bf24c7063d8421b5a1ffa37ff9a836e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - aiohttp
    - cachetools
    - maxminddb
    - pydantic
    - redis-py
    - requests
    - typing_extensions

tests:
  - python:
      imports:
        - guard_core
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Framework-agnostic security engine for the Guard ecosystem.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/rennf93/guard-core

extra:
  recipe-maintainers:
    - thewchan
