schema_version: 1

context:
  version: "4.3.2"

package:
  name: guard-core
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/guard-core/guard_core-${{ version }}.tar.gz
  sha256: 751a0a73ad4d1f9b3a33883218deb0e478d0130cc5da27c3e885ff88d7610554

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - aiohttp
    - cachetools
    - maxminddb
    - pydantic
    - redis-py
    - requests
    - typing_extensions

tests:
  - python:
      imports:
        - guard_core
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Framework-agnostic security engine for the Guard ecosystem.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/rennf93/guard-core

extra:
  recipe-maintainers:
    - thewchan
